In [2]:
import numpy as np
arr = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

arr_sliced = arr[:1, :]
print(arr_sliced, arr_sliced.shape)

[[11 12 13]] (1, 3)


In [3]:
(arr > 15)

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
rand = np.random.randn(2,5)
rand

array([[-1.75325535,  0.20361625,  2.58960948,  1.81109099,  1.10704237],
       [-0.04836822,  0.22694994,  0.53368432,  1.36881157,  0.09779909]])

In [8]:
arr.mean()

22.0